name: Archibus-Automated-Scheduler

on:
  workflow_dispatch:
  # # uncomment to activate scheduler
   schedule:
     - cron: "0 5 * * 1,3,5"

jobs:
  archibus-automated-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: justinj-evans/archibus-automated-scheduler@main # use ./ for local dev.
        with:
          scheduling_args: ${{ secrets.ARCHIBUS_SCHEDULING_ARGS }}
